language: node_js
sudo: false
matrix:
  include:
    - name: "Linux - Node 14"
      os: linux
      node_js: "14"
      env:
        - CXX=g++-4.9
        - CC=gcc-4.9
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-4.9
          - g++-4.9
before_script:
- npm run build-debug
before_deploy:
- npm run build-release
- $(npm bin)/prebuild -r node -t 14.0.0 --include-regex 'better_sqlite3.node$'
- $(npm bin)/prebuild -r electron -t 4.0.0 -t 5.0.0 -t 6.0.0 -t 7.0.0 -t 8.0.0 --include-regex 'better_sqlite3.node$'
deploy:
  provider: releases
  api_key:
    secure: "IjPbQjkHz08xEEWffJAhUNQz1yK48o/n1SwrqHPrcBeXq4FQxHPmc4R2rw58hLpjpa6+WmXH6+YsYX01IQK9B1PHl4fnN2vWEQxvhanCl7FsNCZ9nwIQcgjJ+cw+FGh+P+Ittky+ISikBAL2lCYua5P/6vZ0aHmcw6drY9YABtrImOi1jsG/IWOXwGpGgnmVmwMsxNksD+YU2FX2Bvrh7ckA8/LXp455fOua8ZrqQnEbe23Aky92+H6KMh+eM+y086LRWKmyBSu42j0qaKRxGziz+icCkBNrPcXedvrUJpR4vhDJH05BYCiMPC3IonnUls5J32mUhJc00VZLSuQYC0gwbAzKQGC06q9Kq705Ap94kVfb6psKeoqdGBHt9eQNumb1g3uS09LBs9vI73MStFHIafgz8uCrgdwYQLKrmPvQ/QStXofzqOIpGDBJt1M3SMA7d6S/O+r/jrfzaRkcsQ2Y80+EJgACcxegFSlIu7BQJFO3ehC13gJvZNi268ZChyN/2hN5ywaoCKODcOp/kU8kUQgBa3A4YXv/7ff0tY04v2d4tdZMjpuVaWZu24q7dy1e6DJd/Q7tnFe+AnR6zbebdKTaUc6XQszLon4w6IP+83EUaeAFIM7ZNVeaZZliyM9mkvUGvNfxcZMdAQx49PH8d+/t/pPMet3ETiRaBfw="
  file: prebuilds/*
  file_glob: true
  skip_cleanup: true
  on:
    repo: newmanw/better-sqlite3
    tags: true
    node_js: "14"
